# Generated by Django 4.0 on 2022-02-06 03:32

import App.models.song
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('auto_continue', models.BooleanField(default=True)),
                ('max_song_duration', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(default='Unknown', max_length=200)),
                ('artist', models.CharField(default='Unknown', max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('dance_type', models.CharField(choices=[('Wal', 'Waltz'), ('Tan', 'Tango'), ('Fox', 'Foxtrot'), ('VW', 'Viennese Waltz'), ('Cha', 'Cha-Cha'), ('Rum', 'Rumba'), ('ECS', 'East Coast Swing'), ('Bol', 'Bolero'), ('Mam', 'Mambo'), ('Q', 'Quickstep'), ('Sam', 'Samba'), ('PD', 'Paso Doble'), ('Jiv', 'Jive'), ('Pea', 'Peabody'), ('Bac', 'Bachata'), ('Mer', 'Merengue'), ('Hus', 'Hustle'), ('WCS', 'West Coast Swing'), ('NC2', 'Nite Club 2-Step'), ('C2S', 'Country Two Step')], default='Cha', max_length=10)),
                ('holiday', models.CharField(blank=True, choices=[('Xmas', 'Christmas'), ('Hall', 'Halloween'), ('Jul4', '4th of July'), ('NYE', "New Year's Eve")], default='', max_length=5)),
                ('special', models.CharField(blank=True, choices=[('Featr', 'Feature'), ('Req.O', 'Request Only'), ('Teach', 'Teaching')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SongFileInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=App.models.song.create_valid_filename)),
                ('dance_type', models.CharField(choices=[('Wal', 'Waltz'), ('Tan', 'Tango'), ('Fox', 'Foxtrot'), ('VW', 'Viennese Waltz'), ('Cha', 'Cha-Cha'), ('Rum', 'Rumba'), ('ECS', 'East Coast Swing'), ('Bol', 'Bolero'), ('Mam', 'Mambo'), ('Q', 'Quickstep'), ('Sam', 'Samba'), ('PD', 'Paso Doble'), ('Jiv', 'Jive'), ('Pea', 'Peabody'), ('Bac', 'Bachata'), ('Mer', 'Merengue'), ('Hus', 'Hustle'), ('WCS', 'West Coast Swing'), ('NC2', 'Nite Club 2-Step'), ('C2S', 'Country Two Step')], default='Cha', max_length=10)),
                ('holiday', models.CharField(blank=True, choices=[('Xmas', 'Christmas'), ('Hall', 'Halloween'), ('Jul4', '4th of July'), ('NYE', "New Year's Eve")], default='', max_length=5)),
                ('special', models.CharField(blank=True, choices=[('Featr', 'Feature'), ('Req.O', 'Request Only'), ('Teach', 'Teaching')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_teacher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SongInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.song')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('song', 'playlist', 'order')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='App.SongInPlaylist', to='App.Song'),
        ),
    ]
