# Generated by Django 4.0 on 2022-01-18 00:16

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('audio_link', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.TextField(default='Unknown')),
                ('artist', models.TextField(default='Unknown')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('dance_type', models.CharField(choices=[('Wal', 'Waltz'), ('Tan', 'Tango'), ('Fox', 'Foxtrot'), ('VW', 'Viennese Waltz'), ('Cha', 'Cha-Cha'), ('Rum', 'Rumba'), ('ECS', 'East Coast Swing'), ('Bol', 'Bolero'), ('Mam', 'Mambo'), ('Q', 'Quickstep'), ('Sam', 'Samba'), ('PD', 'Paso Doble'), ('Jiv', 'Jive'), ('Pea', 'Peabody'), ('Bac', 'Bachata'), ('Mer', 'Merengue'), ('Hus', 'Hustle'), ('WCS', 'West Coast Swing'), ('NC2', 'Nite Club 2-Step'), ('C2S', 'Country Two Step')], default='Cha', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SongFileInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=App.models.create_valid_filename)),
                ('dance_type', models.CharField(choices=[('Wal', 'Waltz'), ('Tan', 'Tango'), ('Fox', 'Foxtrot'), ('VW', 'Viennese Waltz'), ('Cha', 'Cha-Cha'), ('Rum', 'Rumba'), ('ECS', 'East Coast Swing'), ('Bol', 'Bolero'), ('Mam', 'Mambo'), ('Q', 'Quickstep'), ('Sam', 'Samba'), ('PD', 'Paso Doble'), ('Jiv', 'Jive'), ('Pea', 'Peabody'), ('Bac', 'Bachata'), ('Mer', 'Merengue'), ('Hus', 'Hustle'), ('WCS', 'West Coast Swing'), ('NC2', 'Nite Club 2-Step'), ('C2S', 'Country Two Step')], default='Cha', max_length=10)),
            ],
        ),
    ]
