# Generated by Django 4.0 on 2022-01-29 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_song_artist_alter_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('auto_continue', models.BooleanField(default=True)),
                ('fade_volume', models.BooleanField(default=False)),
                ('max_song_duration_in_sec', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.song')),
            ],
            options={
                'unique_together': {('song', 'playlist', 'order')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(through='App.SongInPlaylist', to='App.Song'),
        ),
    ]
