# Generated by Django 4.0 on 2022-02-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_playlist_fade_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='holiday',
            field=models.CharField(blank=True, choices=[('Xmas', 'Christmas'), ('Hall', 'Halloween'), ('Jul4', '4th of July'), ('NYE', "New Year's Eve")], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='songfileinput',
            name='holiday',
            field=models.CharField(blank=True, choices=[('Xmas', 'Christmas'), ('Hall', 'Halloween'), ('Jul4', '4th of July'), ('NYE', "New Year's Eve")], default='', max_length=5),
        ),
    ]
