# Generated by Django 4.0 on 2022-02-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_song_dance_type_alter_songfileinput_dance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='special',
        ),
        migrations.RemoveField(
            model_name='songfileinput',
            name='special',
        ),
    ]
