# Generated by Django 4.0 on 2022-02-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_song_special_songfileinput_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='max_song_duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
