# Generated by Django 4.0 on 2022-02-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_song_special_remove_songfileinput_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinplaylist',
            name='feature',
            field=models.BooleanField(default=False),
        ),
    ]
