# Generated by Django 4.0 on 2022-02-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_songinplaylist_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percentage_preferences',
            field=models.JSONField(null=True),
        ),
    ]
