# Generated by Django 4.0 on 2022-02-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_playlist_max_song_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='max_song_duration_in_sec',
        ),
    ]
