# Generated by Django 4.0 on 2022-03-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_user_percentage_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='holiday',
            field=models.CharField(blank=True, choices=[('Jul4', '4th of July'), ('Hween', 'Halloween'), ('Xmas', 'Christmas'), ('NYE', "New Year's Eve")], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='songfileinput',
            name='holiday',
            field=models.CharField(blank=True, choices=[('Jul4', '4th of July'), ('Hween', 'Halloween'), ('Xmas', 'Christmas'), ('NYE', "New Year's Eve")], default='', max_length=5),
        ),
    ]
