# Generated by Django 4.0 on 2022-02-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_playlist_max_song_duration_in_sec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songinplaylist',
            options={'ordering': ['order']},
        ),
    ]
