# Generated by Django 4.0 on 2022-03-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_song_holiday_alter_songfileinput_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='percentage_preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(null=True),
        ),
    ]
