# Generated by Django 4.0 on 2022-03-11 02:31

import App.models.song
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_playlist_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to=App.models.song.create_valid_image_filename),
        ),
    ]
