# Generated by Django 4.0 on 2022-04-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_showcase_or_comp',
            field=models.BooleanField(default=False),
        ),
    ]
