# Generated by Django 4.0 on 2022-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_playlist_is_showcase_or_comp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingSongInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_link', models.CharField(max_length=200)),
                ('image_link', models.CharField(max_length=200)),
                ('dance_type', models.CharField(choices=[('Bac', 'Bachata'), ('Bol', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hus', 'Hustle'), ('Jiv', 'Jive'), ('Mam', 'Mambo/Salsa'), ('Mer', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('PD', 'Paso Doble'), ('Pea', 'Peabody'), ('Q', 'Quickstep'), ('Rum', 'Rumba'), ('Sam', 'Samba'), ('Tan', 'Tango'), ('VW', 'Viennese Waltz'), ('Wal', 'Waltz'), ('WCS', 'West Coast Swing')], default='Cha', max_length=10)),
                ('holiday', models.CharField(blank=True, choices=[('Jul4', '4th of July'), ('Hween', 'Halloween'), ('Xmas', 'Christmas'), ('NYE', "New Year's Eve")], default='', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='image_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
