# Generated by Django 4.0.4 on 2022-05-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_streamingsonginput_song_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyPreviewInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_URI', models.CharField(max_length=100)),
                ('dance_type', models.CharField(choices=[('Bac', 'Bachata'), ('Bol', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hus', 'Hustle'), ('Jiv', 'Jive'), ('Mam', 'Mambo/Salsa'), ('Mer', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('PD', 'Paso Doble'), ('Pea', 'Peabody'), ('Q', 'Quickstep'), ('Rum', 'Rumba'), ('Sam', 'Samba'), ('Tan', 'Tango'), ('VW', 'Viennese Waltz'), ('Wal', 'Waltz'), ('WCS', 'West Coast Swing')], default='Cha', max_length=10)),
                ('holiday', models.CharField(blank=True, choices=[('Jul4', '4th of July'), ('Hween', 'Halloween'), ('Xmas', 'Christmas'), ('NYE', "New Year's Eve")], default='', max_length=5)),
            ],
        ),
    ]
