# Generated by Django 4.0.4 on 2022-05-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_spotifypreviewinput_spotifytrackinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_spotify_token',
            field=models.BooleanField(default=False),
        ),
    ]
