# Generated by Django 4.0.4 on 2022-06-22 01:22

import App.models.song
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_playlist_auto_continue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=App.models.song.create_valid_image_filename),
        ),
    ]
