# Generated by Django 4.0.4 on 2022-07-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_song_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='preferences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
