# Generated by Django 4.0.4 on 2023-03-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_playlist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='category',
            field=models.CharField(choices=[('Norm', 'Normal'), ('Party', 'Party'), ('Show', 'Showcase'), ('Solos', 'Solos')], default='Norm', max_length=10),
        ),
    ]
