# Generated by Django 4.0.4 on 2023-04-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_playlist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songfileinput',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='spotifytrackinput',
            name='holiday',
        ),
        migrations.AlterField(
            model_name='song',
            name='holiday',
            field=models.CharField(blank=True, choices=[('Jul4', '4th of July'), ('Hween', 'Halloween'), ('Xmas', 'Christmas'), ('NYE', "New Year's Eve")], default='', max_length=5, null=True),
        ),
    ]
