# Generated by Django 4.0.4 on 2023-05-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_remove_songfileinput_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='category',
            field=models.CharField(choices=[('Norm', 'Normal'), ('Party', 'Party'), ('Show', 'Showcase')], default='Party', max_length=10),
        ),
    ]
