# Generated by Django 4.2.6 on 2024-01-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_song_bpm_alter_playlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_hates',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='num_likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='num_plays',
            field=models.BigIntegerField(default=0),
        ),
    ]
