# Generated by Django 4.2.6 on 2024-03-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_song_num_hates_song_num_likes_song_num_plays'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_playlists',
            field=models.BigIntegerField(default=0),
        ),
    ]
