# Generated by Django 4.2.6 on 2024-03-09 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_song_num_playlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tagged_Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.song')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tag')),
            ],
            options={
                'unique_together': {('song', 'tag')},
            },
        ),
    ]
