# Generated by Django 4.2.6 on 2024-03-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_rename_tagged_songs_tagged_song_song_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='holiday',
        ),
    ]
