# Generated by Django 4.2.6 on 2024-03-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_remove_song_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='tagged_song',
            order_with_respect_to='tag',
        ),
    ]
