# Generated by Django 4.2.6 on 2024-03-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-title']},
        ),
    ]
