# Generated by Django 4.2.6 on 2025-02-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_alter_tag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='resume_index',
            field=models.IntegerField(default=0),
        ),
    ]
