# Generated by Django 4.2.6 on 2025-11-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_alter_song_dance_type_alter_songfileinput_dance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='alt_dance_type',
            field=models.CharField(choices=[('Bchat', 'Bachata'), ('Bolo', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hust', 'Hustle'), ('Jive', 'Jive'), ('Mambo', 'Mambo / Salsa'), ('Meren', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('Paso', 'Paso Doble'), ('Pbody', 'Peabody'), ('QS', 'Quickstep'), ('Rumba', 'Rumba'), ('Samba', 'Samba'), ('Tango', 'Tango'), ('VWal', 'Viennese Waltz'), ('Waltz', 'Waltz'), ('WCS', 'West Coast Swing'), ('Show', 'Showdance'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='dance_type',
            field=models.CharField(choices=[('Bchat', 'Bachata'), ('Bolo', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hust', 'Hustle'), ('Jive', 'Jive'), ('Mambo', 'Mambo / Salsa'), ('Meren', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('Paso', 'Paso Doble'), ('Pbody', 'Peabody'), ('QS', 'Quickstep'), ('Rumba', 'Rumba'), ('Samba', 'Samba'), ('Tango', 'Tango'), ('VWal', 'Viennese Waltz'), ('Waltz', 'Waltz'), ('WCS', 'West Coast Swing'), ('Show', 'Showdance'), ('N/A', 'N/A')], default='Cha', max_length=10),
        ),
        migrations.AlterField(
            model_name='songfileinput',
            name='dance_type',
            field=models.CharField(choices=[('Bchat', 'Bachata'), ('Bolo', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hust', 'Hustle'), ('Jive', 'Jive'), ('Mambo', 'Mambo / Salsa'), ('Meren', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('Paso', 'Paso Doble'), ('Pbody', 'Peabody'), ('QS', 'Quickstep'), ('Rumba', 'Rumba'), ('Samba', 'Samba'), ('Tango', 'Tango'), ('VWal', 'Viennese Waltz'), ('Waltz', 'Waltz'), ('WCS', 'West Coast Swing'), ('Show', 'Showdance'), ('N/A', 'N/A')], default='Cha', max_length=10),
        ),
        migrations.AlterField(
            model_name='spotifytrackinput',
            name='dance_type',
            field=models.CharField(choices=[('Bchat', 'Bachata'), ('Bolo', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hust', 'Hustle'), ('Jive', 'Jive'), ('Mambo', 'Mambo / Salsa'), ('Meren', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('Paso', 'Paso Doble'), ('Pbody', 'Peabody'), ('QS', 'Quickstep'), ('Rumba', 'Rumba'), ('Samba', 'Samba'), ('Tango', 'Tango'), ('VWal', 'Viennese Waltz'), ('Waltz', 'Waltz'), ('WCS', 'West Coast Swing'), ('Show', 'Showdance'), ('N/A', 'N/A')], default='Cha', max_length=10),
        ),
    ]
