# Generated by Django 4.2.6 on 2025-11-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_alter_song_alt_dance_type_alter_song_dance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='alt_dance_type',
            field=models.CharField(choices=[('ArTan', 'Argentine Tango'), ('Bchat', 'Bachata'), ('Bolo', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hus', 'Hustle'), ('Jive', 'Jive'), ('Mambo', 'Mambo'), ('Meren', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('Paso', 'Paso Doble'), ('Pbody', 'Peabody'), ('Qstep', 'Quickstep'), ('Rumba', 'Rumba'), ('Salsa', 'Salsa'), ('Samba', 'Samba'), ('Tango', 'Tango'), ('VWal', 'Viennese Waltz'), ('Waltz', 'Waltz'), ('WCS', 'West Coast Swing'), ('Show', 'Showdance'), ('NoAlt', 'N/A')], default='NoAlt', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='dance_type',
            field=models.CharField(choices=[('ArTan', 'Argentine Tango'), ('Bchat', 'Bachata'), ('Bolo', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hus', 'Hustle'), ('Jive', 'Jive'), ('Mambo', 'Mambo'), ('Meren', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('Paso', 'Paso Doble'), ('Pbody', 'Peabody'), ('Qstep', 'Quickstep'), ('Rumba', 'Rumba'), ('Salsa', 'Salsa'), ('Samba', 'Samba'), ('Tango', 'Tango'), ('VWal', 'Viennese Waltz'), ('Waltz', 'Waltz'), ('WCS', 'West Coast Swing'), ('Show', 'Showdance'), ('NoAlt', 'N/A')], default='Cha', max_length=10),
        ),
        migrations.AlterField(
            model_name='songfileinput',
            name='dance_type',
            field=models.CharField(choices=[('ArTan', 'Argentine Tango'), ('Bchat', 'Bachata'), ('Bolo', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hus', 'Hustle'), ('Jive', 'Jive'), ('Mambo', 'Mambo'), ('Meren', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('Paso', 'Paso Doble'), ('Pbody', 'Peabody'), ('Qstep', 'Quickstep'), ('Rumba', 'Rumba'), ('Salsa', 'Salsa'), ('Samba', 'Samba'), ('Tango', 'Tango'), ('VWal', 'Viennese Waltz'), ('Waltz', 'Waltz'), ('WCS', 'West Coast Swing'), ('Show', 'Showdance'), ('NoAlt', 'N/A')], default='Cha', max_length=10),
        ),
        migrations.AlterField(
            model_name='spotifytrackinput',
            name='dance_type',
            field=models.CharField(choices=[('ArTan', 'Argentine Tango'), ('Bchat', 'Bachata'), ('Bolo', 'Bolero'), ('Cha', 'Cha-Cha'), ('C2S', 'Country Two Step'), ('ECS', 'East Coast Swing'), ('Fox', 'Foxtrot'), ('Hus', 'Hustle'), ('Jive', 'Jive'), ('Mambo', 'Mambo'), ('Meren', 'Merengue'), ('NC2', 'Night Club 2-Step'), ('Paso', 'Paso Doble'), ('Pbody', 'Peabody'), ('Qstep', 'Quickstep'), ('Rumba', 'Rumba'), ('Salsa', 'Salsa'), ('Samba', 'Samba'), ('Tango', 'Tango'), ('VWal', 'Viennese Waltz'), ('Waltz', 'Waltz'), ('WCS', 'West Coast Swing'), ('Show', 'Showdance'), ('NoAlt', 'N/A')], default='Cha', max_length=10),
        ),
    ]
